answer_question_task:
  description: >
    Answer the following question:    
    {user_question}
    
    When applicable, search for relevant data in the PIRLS 2021 dataset.
    
    When answering, always:    
    - Do not comment on topics outside the area of your expertise.     
    - Ensure that your analysis is accurate and relevant to the research questions.
    - Unless instructed otherwise, explain how you come to your conclusions and provide evidence to support your claims with specific data.
    - Prioritize specific findings from the data engineer in the final output including numbers and percentages
    - Data and numbers should be provided in tables to increase readability.
    - Use markdown format for your final answer.
    - Your answer should need exceed 4 paragraphs. Keep it concise!
    
  expected_output: >
    A clear and concise answer to the question with additional context on correlations and causations with a focus on numbers from the dataset